version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/node18:latest

    container_name: highlevel-node18

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    environment:

      - NODE_ENV=production

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "1647:1647"
    command: >
      sh -c "npm i --force
             pm2-runtime highlevel.js"


#Docker Networks

networks:
  default:
    external:
      name: webskitters
